openapi: 3.0.0
info:
  title: Task API
  version: 1.0.0
  description: API for task management

paths:
  /api/tasks:
    get:
      summary: List all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created

  /api/tasks/{id}:
    put:
      summary: Update a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '200':
          description: Task updated
    
    delete:
      summary: Remove a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task removed

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        due_date:
          type: string
          format: date
        status:
          type: string
          enum: [pending, in_progress, completed]
        user_id:
          type: integer
        user_name:
          type: string
    
    TaskInput:
      type: object
      required:
        - title
        - status
      properties:
        title:
          type: string
        description:
          type: string
        due_date:
          type: string
          format: date
        status:
          type: string
          enum: [pending, in_progress, completed]
        user_id:
          type: integer 